### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by AxaQuilPre** [AxaQuilPre/Pygame_Projects#5]
Leo needs to learn this.

**Comment by DrN1ghtW0lf** [comment]
I'm in progress of learning it, got a few questions I'll be asking here though :
1. in a try except situation like this 

try:
    #does something
expect **Exception**:
    print("There was an error")


Here what is **Exception** ?

**Comment by DrN1ghtW0lf** [comment]
Learning is in progress, going to implement it into hangman maybe even Honai when I'm done studying it
